function pid = startRemoteGazebo(vmIP, vmUser, vmPassword)

    startCmd = sprintf([ ...
        'rm -f %s; ' ...
        'export DISPLAY=:0; ' ...
        'export ROS_MASTER_URI=http://%s:11311; ' ...
        'export ROS_IP=%s; ' ...
        'unset ROS_HOSTNAME; ' ...
        'export GAZEBO_PLUGIN_PATH=/home/user/src/GazeboPlugin/export/lib:$GAZEBO_PLUGIN_PATH; ' ...
        'export LD_LIBRARY_PATH=/home/user/src/GazeboPlugin/export/lib:$LD_LIBRARY_PATH; ' ...
        'source /opt/ros/noetic/setup.bash; ' ...
        'source ~/catkin_ws/devel/setup.bash; ' ...
        'nohup roslaunch mw_vision_example mw_vision_example_newstopsign_cosim.launch ' ...
        '> %s 2>&1 & echo $!'], ...
        vmIP, vmIP, logFile);

    sshStartCmd = sprintf( ...
        'sshpass -p "%s" ssh -o StrictHostKeyChecking=no %s@%s ''%s''', ...
        vmPassword, vmUser, vmIP, startCmd);

    [statusStart, cmdoutStart] = system(sshStartCmd);

    if statusStart ~= 0
        error('Failed to start Gazebo: %s', strtrim(cmdoutStart));
    end

    pid = strtrim(cmdoutStart);

    if isempty(pid) || isnan(str2double(pid))
        error('Gazebo launch did not return a valid PID. Output was: %s', cmdoutStart);
    end

    fprintf('  Gazebo launched! Process ID: %s\n', pid);
    fprintf('  Launch log on VM: %s\n', logFile);
end