function aliases = participantAliases(name)
    n = normalizeFactorName(string(name));

    switch n
        case "w"
            aliases = ["w", "w_gain", "wgain", "controller_gain"];

        case "signdetectionquality"
            aliases = ["sign_detection_quality", ...
                       "signdetectionquality", ...
                       "sdq", ...
                       "sdq_regime", ...
                       "p_regime", ...
                       "perception_regime"];

        case "averagesegmentspeed"
            aliases = ["average_segment_speed", ...
                       "averagesegmentspeed", ...
                       "as", ...
                       "as_regime", ...
                       "s_regime", ...
                       "slippery_regime"];

        otherwise
            aliases = string(name);
    end
end