function evalInfo = makeBaseEvalInfo()
    evalInfo = struct();
    evalInfo.run_validity = "VALID_RUN";
    evalInfo.missing_required_logs = "";
    evalInfo.missing_required_logs_count = 0;
    evalInfo.required_log_stopRobot = false;
    evalInfo.required_log_v = false;
    evalInfo.required_log_w = false;
    evalInfo.required_log_blobX = false;
    evalInfo.required_log_blobSize = false;
    evalInfo.required_log_pose = false;
    evalInfo.metric_validity = struct( ...
        'completed', "INVALID_TECHNICAL", ...
        'completion_time', "INVALID_TECHNICAL", ...
        'average_segment_speed', "INVALID_TECHNICAL", ...
        'sign_detection_quality', "INVALID_TECHNICAL", ...
        'tracking_error_rms', "INVALID_TECHNICAL", ...
        'left_distance_to_sign', "INVALID_TECHNICAL", ...
        'right_distance_to_sign', "INVALID_TECHNICAL", ...
        'stop_distance_to_sign', "INVALID_TECHNICAL", ...
        'time_turning', "INVALID_TECHNICAL", ...
        'time_to_next_blob20_first', "INVALID_TECHNICAL", ...
        'time_to_next_blob20_count', "INVALID_TECHNICAL");
end
