function [mu_raw, w_max, w_sum, T_out] = loadCInputFactorWeights(cfg, spec)
    mu_raw = readFactorMuStarFromCampaign( ...
        spec.factor_weight_source, ...
        {'campaign_C_factor_sensitivity.csv','campaign_C_morris_style_factor_sensitivity.csv'}, ...
        spec.input_factor_names);

    if all(isnan(mu_raw))
        warning(['Could not find structural C factor sensitivity. ' ...
                 'Falling back to ones for SDQ_regime, AS_regime, w_gain.']);
        mu_raw = ones(1, numel(spec.input_factor_names));
    else
        mu_raw(isnan(mu_raw)) = 1.0;
    end

    w_max = normalizeWeightsMax(mu_raw);
    w_sum = normalizeWeightsSum(mu_raw);

    T_out = table( ...
        string(spec.input_factor_names(:)), ...
        mu_raw(:), ...
        w_max(:), ...
        w_sum(:), ...
        'VariableNames', {'Factor','MuStarRaw','WeightMaxNorm','WeightSumNorm'});
end
